control/urls.py
from django.conf.urls import url
from .views import ControlList

from .views import (
    control_list,
    control_create,
)

urlpatterns = [
    # url(r'^$', control_list, name="control_list"),
    url(r'^$', ControlList.as_view(), name="control_list"),
    url(r'^create/$', control_create),
    # url(r'^(?P<id>\d+)/$', group_detail, name="detail"),
    # url(r'^(?P<id>\d+)/edit/$', group_update, name="update"),
    # url(r'^(?P<id>\d+)/delete/$', group_delete),
]

groups/urls.py
from django.conf.urls import url

from .views import (
    group_list,
    group_create,
    group_detail,
    group_update,
    group_delete,
)

urlpatterns = [
    url(r'^$', group_list, name="groups_list"),
    url(r'^create/$', group_create),
    url(r'^(?P<id>\d+)/$', group_detail, name="detail"),
    url(r'^(?P<id>\d+)/edit/$', group_update, name="update"),
    url(r'^(?P<id>\d+)/delete/$', group_delete),
]

posts/urls.py
from django.conf.urls import url

from .views import (
    post_list,
    post_create,
    post_detail,
    post_update,
    post_delete,
)

urlpatterns = [
    url(r'^$', post_list, name="posts_list"),
    url(r'^create/$', post_create),
    url(r'^(?P<id>\d+)/$', post_detail, name="detail"),
    url(r'^(?P<id>\d+)/edit/$', post_update, name="update"),
    url(r'^(?P<id>\d+)/delete/$', post_delete),
]

socialposts/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('registration.auth_urls')),
    url(r'^posts/', include("posts.urls", namespace="posts")),
    url(r'^groups/', include("groups.urls", namespace="groups")),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^', include("control.urls", namespace="control")),


]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block head_title %}Posts Control{% endblock head_title %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <link rel="stylesheet" href='{% static "css/base.css" %}'/>

    <style>
        {% block style %} {% endblock style %}
    </style>
    {% block head_extra %} {% endblock head_extra %}
</head>
<body>

{#{% include "messages_display.html" %}#}
<div class="container">
    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse mb-3">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="#">Social-Posts</a>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link {% if request.resolver_match.url_name == 'control_list' %}active{% endif %}"
                   href="{% url 'control:control_list' %}">Control</a>
                <a class="nav-item nav-link {% if request.resolver_match.url_name == 'groups_list' %}active{% endif %}"
                   href="{% url 'groups:groups_list' %}">Groups</a>
                <a class="nav-item nav-link {% if request.resolver_match.url_name == 'posts_list' %}active{% endif %}"
                   href="{% url 'posts:posts_list' %}">Posts</a>
            </div>

            <div class="navbar-collapse justify-content-md-end">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        {% if user.is_authenticated %}
                            <a class="nav-link" href="{% url 'auth_logout' %}">
                                <strong>{{ user.get_username }}</strong>, logout
                            </a>
                        {% endif %}
                    </li>
{#                       <li class="nav-item dropdown">#}
{#                           <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">#}
{#                               Username#}
{#                           </a>#}
{#                           <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">#}
{#                               <a class="dropdown-item" href="#">Profile</a>#}
{#                               <a class="dropdown-item" href="#">Logout</a>#}
{#                           </div>#}
{#                        </li>#}
                </ul>
            </div>
        </div>
    </nav>
    {% include "messages_display.html" %}
    {% block content %}

    {% endblock content %}
</div>

<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>



</body>
</html>

templates/control_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block head_extra %}
{{ form.media }}
{% endblock head_extra %}

{% block content %}
{{ block.super }}

    <div class="row justify-content-center">
        <div class="col-12">
            <h1>Create Control</h1>
            <hr/>
            <form method="post" action="" enctype="multipart/form-data">{% csrf_token %}
                {{ form | crispy }}
                <input type="submit" class="btn btn-success" value="Create Control"/>
            </form>
        </div>
    </div>
{% endblock content %}

templates/control_list.html
{% extends "base.html" %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-12">
            <h1>{{ title }}</h1>
            <form method="get" action="">
                <div class="input-group mb-3">
                    <input type="text" class="form-control" name="q" placeholder="Search groups and posts" value="{{ request.GET.q }}"/>
                    <span class="input-group-btn">
                    <button class="btn btn-default" type="submit"/><i class="fa fa-search" aria-hidden="true"></i>
                </span>
                </div>
            </form>

            <div class="card mb-2">
                <div class="card-block">
                    <h4 class="card-title">Filters</h4>
                    <div class="card-text">
                        <form class="form-inline" method="post" action="">{% csrf_token %}
                            {{ filter_form }}
                            <button type="submit" class="btn btn-primary">Apply</button>
                        </form>
                    </div>
                </div>
            </div>


            <a href="{{ object_list.get_absolute_url }}create" class="btn btn-primary float-right mb-3"><i class="fa fa-plus"></i> Add new</a>

            <table class="table table-hover table-striped">
                <thead class="thead-inverse">
                <tr>
                    <th class="text-center">Action</th>
                    <th class="text-center">Group</th>
                    {% for value in column %}
                        <th class="text-center">#</th>
                    {% endfor %}
                </tr>
                </thead>

                {% for key, value in controls_per_group.items %}
                    <tr>
                        <td class="text-center"><a class='btn btn-info btn-xs disabled' href="#"><i class="fa fa-pencil"></i></a>
                            <a href="#" class="btn btn-danger btn-xs disabled"><i class="fa fa-trash-o"></i></a></td>
                        <th class="text-center">{{ key }}</th>
                        {% for control in value %}
                            <th class="text-center"><a href="{{ control.post.get_absolute_url }}">{{ control.published | date:"d/m/y" }}<br>{{ control.post.id }}</a></th>
                        {% endfor %}
                    </tr>
                {% endfor %}

            </table>


            <nav aria-label="...">
                <ul class="pagination">
                    {% if object_list.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">Previous</a></li>
                    {% else %}
                        <li class="page-item disabled"><a class="page-link" tabindex="-1" href="">Previous</a></li>
                    {% endif %}

                    {% if object_list.has_previous %}
                        <li class="page-item"><a class="page-link" href="{{ object_list.previous_page_number }}">{{ object_list.previous_page_number }}</a></li>
                    {% else %}
                        <li class="page-item disabled"><a class="page-link" tabindex="-1" href="">&nbsp;</a></li>
                    {% endif %}

                    <li class="page-item active">
                        <a class="page-link" href="#">{{ object_list.number }} <span class="sr-only">(current)</span></a>
                    </li>

                    {% if object_list.has_next %}
                        <li class="page-item"><a class="page-link" href="{{ object_list.next_page_number }}">{{ object_list.next_page_number }}</a></li>
                    {% else %}
                        <li class="page-item disabled"><a class="page-link" tabindex="-1" href="">&nbsp;</a></li>
                    {% endif %}

                    {% if object_list.has_next %}
                        <li class="page-item"><a class="page-link" href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">Next</a></li>
                    {% else %}
                        <li class="page-item disabled"><a class="page-link" tabindex="-1" href="">Next</a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
{% endblock content %}

templates/group_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block head_extra %}
    {{ form.media }}
{% endblock head_extra %}

{% block content %}
    {{ block.super }}

    <div class="row justify-content-center">
        <div class="col-12">
            <h1>Create Group</h1>
            <hr/>
            <form method="post" action="" enctype="multipart/form-data">{% csrf_token %}
                {{ form|crispy }}
                <input type="submit" class="btn btn-success" value="Create Group"/>
            </form>
        </div>
    </div>
{% endblock content %}

templates/group_detail.html
{% extends "base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}

{% block head_title %}
    {{ instance.title }} | {{ block.super }}
{% endblock head_title %}

{% block post_detail_link %}
<li><a href='{{ instance.get_absolute_url }}'>{{ instance.title }}</a></li>
{% endblock %}

{% block content %}
    <div class="row justify-content-center mb-3">
        <div class="col-12">
            <h1>{{ instance.title }}</h1>
            <small class="pull-left" style="padding-left: 10px;"><a href="{{ instance.url }}">{{ instance.url }}</a></small>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-12">
            <div class="card card-success mb-3">
                <div class="card-block" style="padding: 0.5rem">
                    <h4 class="card-title">All Systems Operational</h4>
                    <p class="card-text text-right"><small class="text-muted">Refreshed 39 minutes ago</small></p>

                </div>
            </div>

            <div class="row mb-3">
                <div class="col-12">
                    <div class="card">
                        <div class="card-block">
                            <h4 class="card-title">Admin contacted <span class="badge badge-default pull-right">{{ instance.admin }}</span></h4>
                        </div>
                    </div>

                    <div class="card">
                        <div class="card-block">
                            <h4>Status <span class="badge badge-default pull-right">{{ instance.status }}</span></h4>
                        </div>
                    </div>

                    <div class="card">
                        <div class="card-block">
                            <h4>Post Frequency Allowed <span class="badge badge-default pull-right">{{ instance.frequency }} - {{ instance.frq_scale }}</span></h4>
                        </div>
                    </div>
                </div>
            </div>

            <h2>Posts</h2>
            <table class="table table-hover">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Title</th>
                    <th>Content</th>
                    <th>Published</th>
                </tr>
                </thead>
                <tbody>
                {% for control in controls %}
                    <tr>
                        <td><a href="{{ control.post.get_absolute_url }}">{{ control.post.id }}</a></td>
                        <td><a href="{{ control.post.get_absolute_url }}">{{ control.post }}</a></td>
                        <td><a href="{{ control.post.get_absolute_url }}">{{ control.post.content }}</a></td>
                        <td><a href="{{ control.post.get_absolute_url }}">{{ control.published }}</a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

{% endblock content %}

templates/group_list.html
{% extends "base.html" %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-12">
            <h1>{{ title }}</h1>
            <form method="get" action="">
                <div class="input-group mb-3">
                    <input type="text" class="form-control" name="q" placeholder="Search groups" value="{{ request.GET.q }}"/>
                    <span class="input-group-btn">
                    <button class="btn btn-default" type="submit"/><i class="fa fa-search" aria-hidden="true"></i>
                </span>
                </div>
            </form>

            <a href="{{ object_list.get_absolute_url }}create" class="btn btn-primary float-right mb-3"><i class="fa fa-plus"></i> Add new</a>

            {% for obj in object_list %}
                <div class="card mb-3" style="max-width: 100%; width: 100%;">
                    <div class="card-block">
                        <div class="row">
                            <div class="col-8">
                                <h4 class="card-title"><a href="{{ obj.get_absolute_url }}">{{ obj.title }}</a></h4>
                                <small style="padding-left: 10px;"><a href="{{ obj.url }}">{{ obj.url }}</a></small>
                            </div>
                            <div class="col-4 align-self-center" style="display: flex; align-items: center; justify-content: center;">
                                <a href="{{ obj.get_absolute_url }}" class="btn btn-success">Details</a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}

            <nav aria-label="...">
                <ul class="pagination">
                    {% if object_list.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">Previous</a></li>
                    {% else %}
                        <li class="page-item disabled"><a class="page-link" tabindex="-1" href="">Previous</a></li>
                    {% endif %}

                    {% if object_list.has_previous %}
                        <li class="page-item"><a class="page-link" href="{{ object_list.previous_page_number }}">{{ object_list.previous_page_number }}</a></li>
                    {% else %}
                        <li class="page-item disabled"><a class="page-link" tabindex="-1" href="">&nbsp;</a></li>
                    {% endif %}

                    <li class="page-item active">
                        <a class="page-link" href="#">{{ object_list.number }} <span class="sr-only">(current)</span></a>
                    </li>

                    {% if object_list.has_next %}
                        <li class="page-item"><a class="page-link" href="{{ object_list.next_page_number }}">{{ object_list.next_page_number }}</a></li>
                    {% else %}
                        <li class="page-item disabled"><a class="page-link" tabindex="-1" href="">&nbsp;</a></li>
                    {% endif %}

                    {% if object_list.has_next %}
                        <li class="page-item"><a class="page-link" href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">Next</a></li>
                    {% else %}
                        <li class="page-item disabled"><a class="page-link" tabindex="-1" href="">Next</a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
{% endblock content %}

templates/messages_display.html
{% if messages %}
    <div class="messages">
        <ul class="messages">
            {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>
                    {{ message }}
                </li>
            {% endfor %}
        </ul>
    </div>
{% endif %}

templates/post_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block head_extra %}
    {{ form.media }}
{% endblock head_extra %}

{% block content %}
    {{ block.super }}

    <div class="row justify-content-center">
        <div class="col-12">
            <h1>Create Post</h1>
            <hr/>
            <form method="post" action="" enctype="multipart/form-data">{% csrf_token %}
                {{ form | crispy }}
                <input type="submit" class="btn btn-success" value="Create Post"/>
            </form>
        </div>
    </div>
{% endblock content %}

templates/post_detail.html
{% extends "base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}

{% block head_title %}
    {{ instance.title }} | {{ block.super }}
{% endblock head_title %}

{% block post_detail_link %}
<li><a href='{{ instance.get_absolute_url }}'>{{ instance.title }}</a></li>
{% endblock %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-12">
            <h1 class="mb-3">{{ title }}</h1>
            <div class="card">
                <div class="card-block">
                    <p class="card-text">{{ instance.content }}</p>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/post_list.html
{% extends "base.html" %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-12">
            <h1>{{ title }}</h1>
            <form method="get" action="">
                <div class="input-group mb-3">
                    <input type="text" class="form-control" name="q" placeholder="Search posts" value="{{ request.GET.q }}"/>
                    <span class="input-group-btn">

                    <button class="btn btn-default" type="submit"/><i class="fa fa-search" aria-hidden="true"></i>
                </span>
                </div>
            </form>

            <a href="{{ object_list.get_absolute_url }}create" class="btn btn-primary float-right mb-3"><i class="fa fa-plus"></i> Add new</a>

            {% for obj in object_list %}
                <div class="card mb-3" style="max-width: 100%; width: 100%;">
                    <div class="card-block">
                        <div class="row">
                            <div class="col-8">
                                <h4 class="card-title"><a href="{{ obj.get_absolute_url }}">{{ obj.title }}</a></h4>
                                <p class="card-text">{{ obj.content }}</p>
                            </div>
                            <div class="col-4 align-self-center" style="display: flex; align-items: center; justify-content: center;">
                                <a href="{{ obj.get_absolute_url }}" class="btn btn-success">Details</a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}

            <nav aria-label="...">
                <ul class="pagination">
                    {% if object_list.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">Previous</a></li>
                    {% else %}
                        <li class="page-item disabled"><a class="page-link" tabindex="-1" href="">Previous</a></li>
                    {% endif %}

                    {% if object_list.has_previous %}
                        <li class="page-item"><a class="page-link" href="{{ object_list.previous_page_number }}">{{ object_list.previous_page_number }}</a></li>
                    {% else %}
                        <li class="page-item disabled"><a class="page-link" tabindex="-1" href="">&nbsp;</a></li>
                    {% endif %}

                    <li class="page-item active">
                        <a class="page-link" href="#">{{ object_list.number }} <span class="sr-only">(current)</span></a>
                    </li>

                    {% if object_list.has_next %}
                        <li class="page-item"><a class="page-link" href="{{ object_list.next_page_number }}">{{ object_list.next_page_number }}</a></li>
                    {% else %}
                        <li class="page-item disabled"><a class="page-link" tabindex="-1" href="">&nbsp;</a></li>
                    {% endif %}

                    {% if object_list.has_next %}
                        <li class="page-item"><a class="page-link" href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">Next</a></li>
                    {% else %}
                        <li class="page-item disabled"><a class="page-link" tabindex="-1" href="">Next</a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
{% endblock content %}